version: "3.9"
services:

    redis:
        image: 'bitnami/redis:latest'
        container_name: redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
            - app-networks
     
    api:
        image: crawler-api
        container_name: crawler-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        networks:
            - app-networks
            
networks:
    app-networks:
        driver: bridge
